name: aegislabs
description: "Mobile Aegislabs"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.0.0
  get: ^4.6.6
  dio: ^5.4.3+1
  dio_cookie_manager: ^3.1.1
  retrofit: ^4.2.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  freezed_annotation: any
  json_annotation: ^4.9.0
  get_secure_storage: ^1.0.4
  getwidget: ^4.0.0
  intl: ^0.19.0
  carousel_slider: ^4.2.1
  package_info_plus: ^8.0.0
  device_info_plus: ^10.1.0
  flutter_dotenv: ^5.1.0
  another_flushbar: ^1.12.30
  flutter_svg: ^2.0.10+1
  modal_bottom_sheet: ^3.0.0
  permission_handler: ^11.3.1
  in_app_update: ^4.2.2
  lottie: ^3.1.0
  pinput: ^4.0.0
  cached_network_image: ^3.3.1
  flutter_native_select: ^1.0.1
  flutter_loggy: ^2.0.2
  flutter_loggy_dio: ^3.1.0
  derry: ^1.5.0
  loggy: any
  vector_graphics: any
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  retrofit_generator: ^8.1.0
  freezed: any
  json_serializable: ^6.7.1
  built_value_generator: ^8.9.2
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.4.0
  flutter_flavorizr: ^2.1.5

dependency_overrides:
  intl: ^0.18.0

scripts: derry.yaml

flutter_gen:
  output: lib/gen/
  assets:
    enabled: true
  integrations:
    flutter_svg: true
    lottie: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logo/
    - assets/icons/
    - assets/images/
    - assets/lottie/
    - lib/flavors/
